# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lmcblog?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: hsp

# 日志级别
logging:
  level:
    root: info
    com.lmc: debug
  file:
    path: log/blog-dev.log

# 指定MyBatis映射文件的路径
mybatis:
  type-aliases-package: com.lmc.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
